# Generated by Django 5.1.1 on 2024-09-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselmodel',
            name='background_image',
            field=models.ImageField(upload_to='carousel/'),
        ),
        migrations.AlterField(
            model_name='carouselmodel',
            name='car_image',
            field=models.ImageField(upload_to='carousel/'),
        ),
    ]
