# Generated by Django 5.1.1 on 2024-09-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_carouselmodel_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselmodel',
            name='background_image',
            field=models.ImageField(upload_to='carousel'),
        ),
        migrations.AlterField(
            model_name='carouselmodel',
            name='car_image',
            field=models.ImageField(upload_to='carousel'),
        ),
    ]
